server:
  port: 8088

# DB property Setting 
spring:
    datasource:
        driver-class-name: ${DRIVER}
        url: ${URL}
        username: ${USER}
        password: ${PASSWD}

# Jpa
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.OracleDialect
                show_sql: true
                format_sql: true
                use_sql_comments: true
# auto type : create, none, update  -> 잘안씀
        hibernate:
            ddl-auto: update

# spring:
#     #h2
    
#     datasource:
#         driver-class-name: org.h2.Driver
#         url: jdbc:h2:mem:testdb
#         username: sa
#         password: 
#     h2:
#         console:
#             enabled: true
# # Jpa
#     jpa:
#         hibernate:
#             ddl-auto: update
#         show_sql: true
# token
jwt:
    secret: ${JWT_SECRET_KEY}
        